#! /usr/bin/env bash


set -o errexit
set -o nounset

declare -r PING_CMD=$(type -fp ping)
declare -r PING_ARGS=("-c" "1" "-t" "1")


# Set host status to online
# $1 - ip address
host_is_online() {
  local ip=$1; shift
  echo "online" > ${STATUS_DIR}/$ip
}

# Set host status to offline
# $1 - ip address
host_is_offline() {
  local ip=$1; shift

  echo "offline" > ${STATUS_DIR}/$ip
}

#
# Globals:
#   IPS_TO_CHECK
#   DATA_DIR
#   STATUS_DIR
main() {
  if [[ -z ${IPS_TO_CHECK:-} ]]; then
    echo "IPS_TO_CHECK env var must be set"
    exit 1
  fi

  if [[ -z ${DATA_DIR:-} ]]; then
    echo "DATA_DIR env var must be set"
    exit 1
  fi

  declare -r STATUS_DIR="${DATA_DIR}/status/"

  # Make sure our status directory exists
  mkdir -p ${STATUS_DIR}

  for ip in ${IPS_TO_CHECK}; do
    ping="notstarted or timeout"
    echo "Checking if IP $ip responds."
    ${PING_CMD} ${PING_ARGS[@]} $ip >> /dev/null && ping="pong"
    if [[ ${ping} == "pong" ]]; then
      echo "pong"
      host_is_online $ip
    else
      echo "timeout"
      host_is_offline $ip
    fi
  done
}

main "$@"
