#! /usr/bin/env python

import os
import subprocess
import sys


def check_if_online(host):
  print("Checking if host is online: {}".format(host))
  with open(os.devnull) as dev_null:
    cmd="ping -c 1 -t 1 {}".format(host).split()
    ret_code=subprocess.call(cmd, stdout=dev_null)
    if ret_code == 0:
      return True
    else:
      return False

def set_host_status(host, status):
  host_status_file=os.path.join(os.environ['STATUS_DIR'], host)

  with open(host_status_file, 'w') as f:
    f.write(status)

def make_status_dir():
  status_dir=os.environ['STATUS_DIR']

  if not os.path.isdir(status_dir):
    print("Status directory doesn't exist, creating: {}".format(status_dir))
    os.makedirs(status_dir)

def is_anybody_home(hosts_to_check):
  any_online=False

  for host in hosts_to_check:
    online_result=check_if_online(host)
    print("Result: {}".format(online_result))

    if online_result:
      set_host_status(host, "online")
      any_online=True
    else:
      set_host_status(host, "offline")

  return any_online

def main():
  try:
    status_dir=os.environ["STATUS_DIR"].split()
  except KeyError:
    print("STATUS_DIR env var required")
    sys.exit(1)

  try:
    hosts_to_check=os.environ["HOSTS_TO_CHECK"].split()
  except KeyError:
    print("HOST_TO_CHECK env var required")
    sys.exit(1)

  make_status_dir()

  anybody_home=is_anybody_home(hosts_to_check)
  print("Is anybody home? {}".format(anybody_home))

main()
