#! /usr/bin/env bash


set -o errexit
set -o nounset

declare -r PING_CMD=$(type -fp ping)
declare -r PING_ARGS=("-c" "1" "-t" "1")

if [[ -z ${IPS_TO_CHECK:-} ]]; then
  echo "IPS_TO_CHECK env var must be set"
  exit 1
fi

for ip in ${IPS_TO_CHECK}; do
  ping="notstarted or timeout"
  echo "Checking if IP $ip responds."
  ${PING_CMD} ${PING_ARGS[@]} $ip >> /dev/null && ping="pong"
  if [[ ${ping} == "pong" ]]; then
    echo "pong"
  else
    echo "timeout"
  fi
done
